### ISSUE TITLE
KeyError: 'songTitle'

### ISSUE THREAD

**Issue by MIM1C7MBDWLA0JZLCJD8** [1fge/my-pandora-likes#1]
Hi,
I'm a long-time programmer, but new to python.

I downloaded and installed My-Pandora-Likes on Windows 10, and it is able to log in and start the download of likes, but I get the following error.

Any idea what I'm doing wrong?

> Browser Login Attempt (1)
Successfully Logged In!

> Total Liked Songs: 447

> Fetching Songs from 0 to 100...
Fetching Songs from 100 to 200...
Fetching Songs from 200 to 300...
Fetching Songs from 300 to 400...
Traceback (most recent call last):
  File "pandora_likes.py", line 166, in <module>
    downloader.download_likes()
  File "pandora_likes.py", line 157, in download_likes
    parsed_songs = self.compile_liked_songs(auth_token, csrf_token, song_count, webname)
  File "pandora_likes.py", line 115, in compile_liked_songs
    parsed_songs = self.parse_songs(parsed_songs, songs)
  File "pandora_likes.py", line 94, in parse_songs
    "title": song["songTitle"],
KeyError: 'songTitle'

**Comment by 1fge** [comment]
Hi, thanks a lot for creating this issue! From what I can tell, this seems like an edge case that I hadn't handled for. I added a few changes with the most recent commit so you should no longer get that error.

**Comment by MIM1C7MBDWLA0JZLCJD8** [comment]
Hi,

It works great now! Thanks for the quick fix!

I've been playing around with it for a few hours, but couldn't fix it on my own. I have some ideas on what was happening, but don't know Python enough to track it down.

If you have a moment, I'd really appreciate knowing what was happening. If you could give me an idea on how to display the song data that's giving the parsing error, that would help me to understand it better.

Don't feel like you have to do any more, though. This is a great solution, and your fix is very much appreciated.

Thanks!

;)

**Comment by 1fge** [comment]
Not a problem! So it seems like one of the songs is causing an issue which then kills the entire program. The dictionary representing that particular song doesn't have the `songTitle` key (and perhaps other required keys), so when the program tries to access it, the `Key Error` Exception is raised. 

If you want to see the particular song that's causing the problem, you can modify the `except` block in the most recent commit to print what the data of the problematic song:

```python
...
except KeyError:
    print(song)
...
```
If you are able to display the data of that song, would mind posting it here? I'm very curious to see why that song is so much different.

**Comment by MIM1C7MBDWLA0JZLCJD8** [comment]
Hi, thanks for the info!

The two songs that are throwing the error are below.

I've been poking around with the output and found some interesting things. My Pandora account says I have 492 thumbs up, but python says I only have 448.

Also, it looks like each thumb is assigned a unique ID by Pandora. When I look at the songs returned to python, there are a bunch of duplicates. Not sure why the API would return duplicates, or if Pandora actually had dupes in their database...

I'm wondering if there are issues with their API, or if something else is causing these two issues...

I would think it's not the fault of pandora_likes.py, as you're just dealing with the data the API returns.

Another interesting thing, pandora_likes.py was using an incorrect name for the json file. I went into my Pandora account and realized I had misspelled my name when I signed up, so I fixed it. But even though it's fixed in Pandora, the API is still returning the misspelled name! I'm guessing the API is not returning real time data, and it will get updated at some point.

Which now makes me wonder how long it takes to start returning a new thumbs up?

Interesting the things you find when you start playing around!

I found some other things in the data they return, if you're interested I'll post them as well.

Thanks again for your responses! ;)

{'feedbackId': '6412874593698742', 'feedbackDateCreated': '2016-07-17T18:04:05.348Z', 'isPositive': True, 'stationId': '2810577692053624366', 'stationName': 'Taylor Taylor Swift Radio', 'stationType': 'SEEDED_STATION'}
** Error Parsing Song, Skipping

{'feedbackId': '6412874592574168', 'feedbackDateCreated': '2016-07-16T19:24:44.102Z', 'isPositive': True, 'stationId': '2810577692053624366', 'stationName': 'Taylor Taylor Swift Radio', 'stationType': 'SEEDED_STATION'}
** Error Parsing Song, Skipping

**Comment by MIM1C7MBDWLA0JZLCJD8** [comment]
I just checked on how long it takes for new thumbs to be returned by the API.

I logged into my mobile and my desktop at the same time, and went to my profile on the desktop to see how many thumbs up were listed.

I then thumbs-up on two songs on my mobile, refreshed the desktop page and the new thumbs were listed.

I then ran pandora_likes.py and the new thumbs were returned!

So, it looks like thumbs-up are stored in real time, that the mobile and desktop are in sync in real time, and the API returns data in real time.

It's still returning my misspelled name, though!

**Comment by 1fge** [comment]
Thanks for sending over those two songs. And that's very strange regarding the discrepancies in liked songs. Maybe it has to do with licensing or something similar so they no longer display the details for that liked song? Very interesting indeed. 

Regarding the name, I just use the `webname` value that's returned from their API after logging in so that might take some time to change over. But yeah it's really fascinating viewing all of the different data Pandora stores regarding liked songs, stations, and seeing some of how their song picking process works. Even just viewing the requests in browser after logging in reveals so much interesting information.
